server:
  port: 8082

spring:
  application:
    name: url-service
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/url_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}